### ISSUE TITLE
undefined method `parent' for AnyAppName::Application:Class (NoMethodError) Did you mean?  present?

### ISSUE THREAD

**Issue by MrDearg** [morshedalam/rename#13] opened 2021-07-26 10:23 UTC
I'm getting this error when trying to run the generator in rails 6.1.3.1

```undefined method `parent' for AnyAppName::Application:Class (NoMethodError) Did you mean?  present?```

**Comment by morshedalam** [comment] 2021-07-26 10:25
Please let me know the gem version you are using

sent from my mobile

**Comment by morshedalam** [comment] 2021-08-17 17:56
@MrDearg Unable to reproduce! Just tested again with the same rails version you mentioned.

Closing the issue as I think you were trying with older version of the gem. Please try with latest version and post with Gems list if you still experience the issue and can open the issue.

**Closed by morshedalam** 2021-08-17 17:56 UTC
